<?php
declare(strict_types=1);
session_start();
require_once __DIR__ . '/../db.php';
if (!isset($_SESSION['admin_id'])) { header('Location: index.php'); exit; }
function h(string $value): string { return htmlspecialchars($value, ENT_QUOTES, 'UTF-8'); }
$topCities = $pdo->query('SELECT city, country, COUNT(*) AS total FROM stops GROUP BY city, country ORDER BY total DESC, city LIMIT 8')->fetchAll();
$topActivities = $pdo->query('SELECT name, activity_type, COUNT(*) AS total, COALESCE(SUM(estimated_cost), 0) AS cost FROM activities GROUP BY name, activity_type ORDER BY total DESC, name LIMIT 8')->fetchAll();
$monthlyTrips = $pdo->query('SELECT DATE_FORMAT(created_at, "%Y-%m") AS month, COUNT(*) AS total FROM trips GROUP BY month ORDER BY month DESC LIMIT 6')->fetchAll();
$engagement = ['users' => (int)$pdo->query('SELECT COUNT(*) FROM users WHERE role = "user"')->fetchColumn(), 'active_users' => (int)$pdo->query('SELECT COUNT(DISTINCT user_id) FROM trips')->fetchColumn(), 'trips' => (int)$pdo->query('SELECT COUNT(*) FROM trips')->fetchColumn(), 'planned_items' => (int)$pdo->query('SELECT COUNT(*) FROM stops') ->fetchColumn() + (int)$pdo->query('SELECT COUNT(*) FROM activities')->fetchColumn()];
$maxCity = max(1, (int)($topCities[0]['total'] ?? 1));
$maxActivity = max(1, (int)($topActivities[0]['total'] ?? 1));
?><!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>GlobeTrotter Analytics</title><link rel="stylesheet" href="admin.css"></head><body><header class="admin-header"><div><p class="eyebrow">GlobeTrotter</p><h1>Analytics</h1></div><div class="header-right">Signed in as <?php echo h((string)$_SESSION['admin_name']); ?> <a href="index.php">Back to admin</a></div></header><main class="analytics-main"><section class="stats"><div><span>Registered users</span><strong><?php echo $engagement['users']; ?></strong></div><div><span>Users with trips</span><strong><?php echo $engagement['active_users']; ?></strong></div><div><span>Total trips</span><strong><?php echo $engagement['trips']; ?></strong></div><div><span>Planned items</span><strong><?php echo $engagement['planned_items']; ?></strong></div></section><div class="chart-grid"><section class="panel"><h2>Most selected cities</h2><?php foreach ($topCities as $city): ?><div class="bar-row"><span><?php echo h($city['city']); ?><?php if ($city['country']): ?>, <?php echo h($city['country']); ?><?php endif; ?></span><div class="bar-track"><i style="width:<?php echo ((int)$city['total'] / $maxCity) * 100; ?>%"></i></div><b><?php echo $city['total']; ?></b></div><?php endforeach; ?><?php if (!$topCities): ?><p class="muted">No city data yet.</p><?php endif; ?></section><section class="panel"><h2>Most added activities</h2><?php foreach ($topActivities as $activity): ?><div class="bar-row"><span><?php echo h($activity['name']); ?></span><div class="bar-track"><i style="width:<?php echo ((int)$activity['total'] / $maxActivity) * 100; ?>%"></i></div><b><?php echo $activity['total']; ?></b></div><?php endforeach; ?><?php if (!$topActivities): ?><p class="muted">No activity data yet.</p><?php endif; ?></section></div><section class="panel"><h2>Trips created by month</h2><div class="month-list"><?php foreach ($monthlyTrips as $month): ?><div><span><?php echo h($month['month']); ?></span><strong><?php echo $month['total']; ?> trips</strong></div><?php endforeach; ?><?php if (!$monthlyTrips): ?><p class="muted">No trip data yet.</p><?php endif; ?></div></section></main></body></html>
