<?php
declare(strict_types=1);
session_start();
require_once __DIR__ . '/../db.php';
ob_start(static function (string $output): string {
    $output = str_replace(['EUR ', '€'], ['Rs ', 'Rs '], $output);
    return str_replace('>Expenses</a><a href="../">', '>Expenses</a><a href="analytics.php">Analytics</a><a href="../">', $output);
});
function h(string $value): string { return htmlspecialchars($value, ENT_QUOTES, 'UTF-8'); }
if (isset($_GET['logout'])) { session_unset(); session_destroy(); header('Location: ../login.php'); exit; }
$loginError = '';
if (!isset($_SESSION['admin_id']) && $_SERVER['REQUEST_METHOD'] === 'POST') {
    $statement = $pdo->prepare('SELECT id, name, password_hash, role FROM users WHERE email = :email LIMIT 1');
    $statement->execute(['email' => trim((string)($_POST['email'] ?? ''))]);
    $admin = $statement->fetch();
    if ($admin && $admin['role'] === 'admin' && password_verify((string)($_POST['password'] ?? ''), $admin['password_hash'])) { session_regenerate_id(true); $_SESSION['user_id'] = (int)$admin['id']; $_SESSION['user_name'] = $admin['name']; $_SESSION['user_role'] = 'admin'; $_SESSION['admin_id'] = (int)$admin['id']; $_SESSION['admin_name'] = $admin['name']; header('Location: index.php'); exit; }
    $loginError = 'The email or password is incorrect.';
}
if (!isset($_SESSION['admin_id'])):
?><!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>GlobeTrotter Admin Login</title><link rel="stylesheet" href="admin.css"></head><body class="login-page"><main class="login-box"><p class="eyebrow">GlobeTrotter</p><h1>Admin login</h1><p class="muted">Sign in to manage the travel planning platform.</p><?php if ($loginError): ?><p class="message error"><?php echo h($loginError); ?></p><?php endif; ?><form method="post"><label>Email<input type="email" name="email" required></label><label>Password<input type="password" name="password" required></label><button type="submit">Sign in</button></form><p class="hint">Demo email: admin@globetrotter.local<br>Demo password: admin123</p></main></body></html><?php exit; endif;
$message = ''; $error = '';
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $action = (string)($_POST['action'] ?? '');
    try {
        if ($action === 'add_user') { $statement = $pdo->prepare('INSERT INTO users (name, email, password_hash, role) VALUES (:name, :email, :password_hash, :role)'); $statement->execute(['name' => trim((string)$_POST['name']), 'email' => trim((string)$_POST['email']), 'password_hash' => password_hash((string)$_POST['password'], PASSWORD_DEFAULT), 'role' => $_POST['role'] === 'admin' ? 'admin' : 'user']); $message = 'User added successfully.'; }
        elseif ($action === 'delete_user') { $statement = $pdo->prepare('DELETE FROM users WHERE id = :id AND role = "user"'); $statement->execute(['id' => (int)$_POST['id']]); $message = 'User removed successfully.'; }
        elseif ($action === 'add_trip') { $statement = $pdo->prepare('INSERT INTO trips (user_id, name, start_date, end_date, destination, description) VALUES (:user_id, :name, :start_date, :end_date, :destination, :description)'); $statement->execute(['user_id' => (int)$_POST['user_id'], 'name' => trim((string)$_POST['name']), 'start_date' => $_POST['start_date'], 'end_date' => $_POST['end_date'], 'destination' => trim((string)$_POST['destination']), 'description' => trim((string)$_POST['description'])]); $message = 'Trip added successfully.'; }
        elseif ($action === 'delete_trip') { $statement = $pdo->prepare('DELETE FROM trips WHERE id = :id'); $statement->execute(['id' => (int)$_POST['id']]); $message = 'Trip removed successfully.'; }
        elseif ($action === 'add_stop') { $statement = $pdo->prepare('INSERT INTO stops (trip_id, city, country, arrival_date, departure_date, position) VALUES (:trip_id, :city, :country, :arrival_date, :departure_date, 0)'); $statement->execute(['trip_id' => (int)$_POST['trip_id'], 'city' => trim((string)$_POST['city']), 'country' => trim((string)$_POST['country']), 'arrival_date' => $_POST['arrival_date'] ?: null, 'departure_date' => $_POST['departure_date'] ?: null]); $message = 'Stop added successfully.'; }
        elseif ($action === 'delete_stop') { $statement = $pdo->prepare('DELETE FROM stops WHERE id = :id'); $statement->execute(['id' => (int)$_POST['id']]); $message = 'Stop removed successfully.'; }
        elseif ($action === 'add_activity') { $statement = $pdo->prepare('INSERT INTO activities (stop_id, name, activity_type, estimated_cost, start_time, notes) VALUES (:stop_id, :name, :activity_type, :estimated_cost, :start_time, :notes)'); $statement->execute(['stop_id' => (int)$_POST['stop_id'], 'name' => trim((string)$_POST['name']), 'activity_type' => trim((string)$_POST['activity_type']), 'estimated_cost' => (float)$_POST['estimated_cost'], 'start_time' => $_POST['start_time'] ?: null, 'notes' => trim((string)$_POST['notes'])]); $message = 'Activity added successfully.'; }
        elseif ($action === 'delete_activity') { $statement = $pdo->prepare('DELETE FROM activities WHERE id = :id'); $statement->execute(['id' => (int)$_POST['id']]); $message = 'Activity removed successfully.'; }
        elseif ($action === 'add_expense') { $statement = $pdo->prepare('INSERT INTO expenses (trip_id, category, label, amount) VALUES (:trip_id, :category, :label, :amount)'); $statement->execute(['trip_id' => (int)$_POST['trip_id'], 'category' => $_POST['category'], 'label' => trim((string)$_POST['label']), 'amount' => (float)$_POST['amount']]); $message = 'Expense added successfully.'; }
        elseif ($action === 'delete_expense') { $statement = $pdo->prepare('DELETE FROM expenses WHERE id = :id'); $statement->execute(['id' => (int)$_POST['id']]); $message = 'Expense removed successfully.'; }
    } catch (PDOException $exception) { $error = 'This action could not be completed. Check that the data is valid and unique.'; }
}
$section = (string)($_GET['section'] ?? 'dashboard');
$users = $pdo->query('SELECT id, name, email, role, created_at FROM users ORDER BY created_at DESC')->fetchAll();
$userOptions = $pdo->query('SELECT id, name FROM users WHERE role = "user" ORDER BY name')->fetchAll();
$trips = $pdo->query('SELECT trips.id, trips.name, trips.destination, trips.start_date, trips.end_date, users.name AS owner FROM trips JOIN users ON users.id = trips.user_id ORDER BY trips.created_at DESC')->fetchAll();
$stops = $pdo->query('SELECT stops.id, stops.city, stops.country, trips.name AS trip_name FROM stops JOIN trips ON trips.id = stops.trip_id ORDER BY stops.id DESC')->fetchAll();
$stopOptions = $pdo->query('SELECT stops.id, stops.city, trips.name AS trip_name FROM stops JOIN trips ON trips.id = stops.trip_id ORDER BY trips.name, stops.city')->fetchAll();
$activities = $pdo->query('SELECT activities.id, activities.name, activities.activity_type, activities.estimated_cost, stops.city FROM activities JOIN stops ON stops.id = activities.stop_id ORDER BY activities.id DESC')->fetchAll();
$expenses = $pdo->query('SELECT expenses.id, expenses.label, expenses.category, expenses.amount, trips.name AS trip_name FROM expenses JOIN trips ON trips.id = expenses.trip_id ORDER BY expenses.id DESC')->fetchAll();
$stats = ['users' => (int)$pdo->query('SELECT COUNT(*) FROM users WHERE role = "user"')->fetchColumn(), 'trips' => (int)$pdo->query('SELECT COUNT(*) FROM trips')->fetchColumn(), 'stops' => (int)$pdo->query('SELECT COUNT(*) FROM stops')->fetchColumn(), 'activities' => (int)$pdo->query('SELECT COUNT(*) FROM activities')->fetchColumn(), 'expenses' => (float)$pdo->query('SELECT COALESCE(SUM(amount), 0) FROM expenses')->fetchColumn()];
?><!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>GlobeTrotter Admin</title><link rel="stylesheet" href="admin.css"></head><body><header class="admin-header"><div><p class="eyebrow">GlobeTrotter</p><h1>Administration</h1></div><div class="header-right">Signed in as <?php echo h((string)$_SESSION['admin_name']); ?> <a href="?logout=1">Log out</a></div></header><div class="admin-layout"><aside class="admin-nav"><p class="nav-title">Manage</p><a class="<?php echo $section === 'dashboard' ? 'selected' : ''; ?>" href="?section=dashboard">Dashboard</a><a class="<?php echo $section === 'users' ? 'selected' : ''; ?>" href="?section=users">Users</a><a class="<?php echo $section === 'trips' ? 'selected' : ''; ?>" href="?section=trips">Trips</a><a class="<?php echo $section === 'stops' ? 'selected' : ''; ?>" href="?section=stops">Stops</a><a class="<?php echo $section === 'activities' ? 'selected' : ''; ?>" href="?section=activities">Activities</a><a class="<?php echo $section === 'expenses' ? 'selected' : ''; ?>" href="?section=expenses">Expenses</a><a href="../">Open user site</a></aside><main class="admin-main"><?php if ($message): ?><p class="message success"><?php echo h($message); ?></p><?php endif; ?><?php if ($error): ?><p class="message error"><?php echo h($error); ?></p><?php endif; ?>
<?php if ($section === 'dashboard'): ?><h2>Dashboard</h2><p class="muted">A live view of information stored in the database.</p><section class="stats"><div><span>Users</span><strong><?php echo $stats['users']; ?></strong></div><div><span>Trips</span><strong><?php echo $stats['trips']; ?></strong></div><div><span>Stops</span><strong><?php echo $stats['stops']; ?></strong></div><div><span>Activities</span><strong><?php echo $stats['activities']; ?></strong></div><div><span>Expenses</span><strong>EUR <?php echo number_format($stats['expenses'], 2); ?></strong></div></section><section class="panel"><h3>Administration tools</h3><p class="muted">Use the navigation to add or remove users, trips, itinerary stops, activities, and expenses. Every change is saved immediately in MySQL.</p></section>
<?php elseif ($section === 'users'): ?><h2>Users</h2><p class="muted">Manage accounts that use the platform.</p><section class="panel"><h3>Add user</h3><form class="form-grid" method="post"><input type="hidden" name="action" value="add_user"><label>Name<input name="name" required></label><label>Email<input type="email" name="email" required></label><label>Password<input type="password" name="password" required minlength="6"></label><label>Role<select name="role"><option value="user">User</option><option value="admin">Admin</option></select></label><button type="submit">Add user</button></form></section><section class="panel"><h3>All users</h3><?php include __DIR__ . '/users-table.php'; ?></section>
<?php elseif ($section === 'trips'): ?><h2>Trips</h2><p class="muted">Create and remove user journeys.</p><section class="panel"><h3>Add trip</h3><form class="form-grid" method="post"><input type="hidden" name="action" value="add_trip"><label>Owner<select name="user_id" required><?php foreach ($userOptions as $user): ?><option value="<?php echo $user['id']; ?>"><?php echo h($user['name']); ?></option><?php endforeach; ?></select></label><label>Trip name<input name="name" required></label><label>Start date<input type="date" name="start_date" required></label><label>End date<input type="date" name="end_date" required></label><label>Destination<input name="destination"></label><label>Description<textarea name="description"></textarea></label><button type="submit">Add trip</button></form></section><section class="panel"><h3>All trips</h3><?php include __DIR__ . '/trips-table.php'; ?></section>
<?php elseif ($section === 'stops'): ?><h2>Stops</h2><p class="muted">Manage cities inside trips.</p><section class="panel"><h3>Add stop</h3><form class="form-grid" method="post"><input type="hidden" name="action" value="add_stop"><label>Trip<select name="trip_id" required><?php foreach ($trips as $trip): ?><option value="<?php echo $trip['id']; ?>"><?php echo h($trip['name']); ?></option><?php endforeach; ?></select></label><label>City<input name="city" required></label><label>Country<input name="country"></label><label>Arrival<input type="date" name="arrival_date"></label><label>Departure<input type="date" name="departure_date"></label><button type="submit">Add stop</button></form></section><section class="panel"><h3>All stops</h3><?php include __DIR__ . '/stops-table.php'; ?></section>
<?php elseif ($section === 'activities'): ?><h2>Activities</h2><p class="muted">Manage experiences connected to itinerary stops.</p><section class="panel"><h3>Add activity</h3><form class="form-grid" method="post"><input type="hidden" name="action" value="add_activity"><label>Stop<select name="stop_id" required><?php foreach ($stopOptions as $stop): ?><option value="<?php echo $stop['id']; ?>"><?php echo h($stop['trip_name'] . ' - ' . $stop['city']); ?></option><?php endforeach; ?></select></label><label>Name<input name="name" required></label><label>Type<input name="activity_type"></label><label>Cost<input type="number" name="estimated_cost" min="0" step="0.01" value="0"></label><label>Start time<input type="time" name="start_time"></label><label>Notes<textarea name="notes"></textarea></label><button type="submit">Add activity</button></form></section><section class="panel"><h3>All activities</h3><?php include __DIR__ . '/activities-table.php'; ?></section>
<?php elseif ($section === 'expenses'): ?><h2>Expenses</h2><p class="muted">Track estimated costs for each trip.</p><section class="panel"><h3>Add expense</h3><form class="form-grid" method="post"><input type="hidden" name="action" value="add_expense"><label>Trip<select name="trip_id" required><?php foreach ($trips as $trip): ?><option value="<?php echo $trip['id']; ?>"><?php echo h($trip['name']); ?></option><?php endforeach; ?></select></label><label>Category<select name="category"><option>transport</option><option>stay</option><option>activities</option><option>meals</option><option>other</option></select></label><label>Label<input name="label" required></label><label>Amount<input type="number" name="amount" min="0" step="0.01" required></label><button type="submit">Add expense</button></form></section><section class="panel"><h3>All expenses</h3><?php include __DIR__ . '/expenses-table.php'; ?></section><?php endif; ?></main></div></body></html>
